org.gradle.jvmargs = -Xmx6G
org.gradle.parallel = true

# Minecraft Properties
minecraft_version = 26.2-pre-4
minecraft_version_supported = [26.1,26.2]
minecraft_version_filter = any
minecraft_version_min_excl = 1.21.11
minecraft_version_max_excl =

# File Name
minecraft_version_name = 26.1(2)
archives_base_name = MoreBarrelVariants

# Mod Properties
mod_id=more_barrel_variants
mod_name=More Barrel Variants
mod_name_short=More Barrel Variants
mod_license=CC-BY-NC-SA-4.0
mod_version = 2.0.5
mod_description=Adding Barrel variants to Minecraft
group_id=de.pnku
modrinth_project_id = g4AhyGgi
curseforge_project_id = 1058391

# Dependencies
#every_compat_version=1.21-2.11.30
#moonlight_version=1.21-2.29.20
#wilder_wild_version=4.2.1
#frozen_lib_version=2.2.4