org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Minecraft Properties
minecraft_version = 1.21.11
minecraft_version_supported = [1.21.4,1.21.11]
minecraft_version_lower = 1.21.3
minecraft_version_upper =

# File Name
minecraft_version_name = 1.21.4(-11)
archives_base_name = MoreBarrelVariants

## Mod Properties

mod_id=lolmblv
mod_name=More Barrel Variants
mod_name_short=More Barrel Variants
mod_license=MIT
mod_version=1.8.0
mod_group_id=de.pnku.mblv
mod_authors=pnku, LieOnLion
mod_description=Adding Barrel variants to Minecraft

# Quad Properties
quad_version=1.2.0